In [1]:
import yfinance as yf
import pandas as pd

In [2]:
data = pd.read_csv('apollo_hospitals.csv')

In [3]:
data

,Price,Adj Close,Close,High,Low,Open,Volume
0,Ticker,APOLLOHOSP.NS,APOLLOHOSP.NS,APOLLOHOSP.NS,APOLLOHOSP.NS,APOLLOHOSP.NS,APOLLOHOSP.NS
1,Date,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01,1410.9296875,1460.800048828125,1480.0,1449.0,1458.5,107024
3,2016-01-04,1400.594482421875,1450.0999755859375,1470.0,1445.0,1450.4000244140625,121226
4,2016-01-05,1418.3665771484375,1468.5,1497.699951171875,1432.4000244140625,1451.0,667535
...,...,...,...,...,...,...,...
2581,2026-06-11,8493.0,8493.0,8531.0,8425.0,8478.0,314597
2582,2026-06-12,8498.0,8498.0,8558.0,8440.0,8535.0,276444
2583,2026-06-15,8468.5,8468.5,8534.0,8391.0,8526.0,358223
2584,2026-06-16,8390.5,8390.5,8517.0,8382.0,8468.5,263172
2585,2026-06-17,8427.5,8427.5,8464.5,8385.0,8390.5,185434

In [4]:
data = data.iloc[2:].reset_index(drop=True)
data = data.rename(columns={'Price':'Date'})
data.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2016-01-01,1410.9296875,1460.800048828125,1480.0,1449.0,1458.5,107024
1,2016-01-04,1400.594482421875,1450.0999755859375,1470.0,1445.0,1450.4000244140625,121226
2,2016-01-05,1418.3665771484375,1468.5,1497.699951171875,1432.4000244140625,1451.0,667535
3,2016-01-06,1405.6654052734375,1455.3499755859375,1480.0,1445.0999755859375,1455.0,233987
4,2016-01-07,1348.969482421875,1396.6500244140625,1450.0,1380.199951171875,1431.0,184861

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2584 entries, 0 to 2583
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2584 non-null   datetime64[ns]
 1   Adj Close  2584 non-null   float64
 2   Close      2584 non-null   float64
 3   High       2584 non-null   float64
 4   Low        2584 non-null   float64
 5   Open       2584 non-null   float64
 6   Volume     2584 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 141.4 KB

In [6]:
data['Date'] = pd.to_datetime(data['Date'],errors='coerce')

In [8]:
data['Adj Close'] = pd.to_numeric(data['Adj Close'],errors='coerce')

In [10]:
data['Close'] = pd.to_numeric(data['Close'],errors='coerce')

In [11]:
data['High'] = pd.to_numeric(data['High'],errors='coerce')

In [13]:
data['Low'] = pd.to_numeric(data['Low'],errors='coerce')

In [14]:
data['Open'] = pd.to_numeric(data['Open'],errors='coerce')

In [15]:
data['Volume'] = pd.to_numeric(data['Volume'],errors='coerce')

In [18]:
data.isnull().sum()

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [19]:
data.duplicated().sum()

0

In [20]:
data.head()

,Date,Adj Close,Close,High,Low,Open,Volume
0,2016-01-01,1410.929688,1460.800049,1480.000000,1449.000000,1458.500000,107024
1,2016-01-04,1400.594482,1450.099976,1470.000000,1445.000000,1450.400024,121226
2,2016-01-05,1418.366577,1468.500000,1497.699951,1432.400024,1451.000000,667535
3,2016-01-06,1405.665405,1455.349976,1480.000000,1445.099976,1455.000000,233987
4,2016-01-07,1348.969482,1396.650024,1450.000000,1380.199951,1431.000000,184861

In [22]:
data.to_excel('apollo.xlsx',index=False)